- **Nom**: David Morillo Massagué
- **NIU**: 1666540

### 1. We have an encrypted message “VRBXQSHSLQLOOR”, which has been encrypted using a simple substitution (mono-alphabetic) cipher, as ci = mi + k (mod n) with an unkown k and n = 26

In [61]:
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

def encrypt(text: str, key: int) -> str:
    text.upper()
    encrypted = ""
    for i in range(len(text)):
        if text[i] in alphabet:
            encrypted += alphabet[(alphabet.index(text[i]) + key) % 26]
        else:
            encrypted += text[i]
    return encrypted

def decrypt(text: str, key: int) -> str:
    text.upper()
    decrypted = ""
    for i in range(len(text)):
        if text[i] in alphabet:
            decrypted += alphabet[(alphabet.index(text[i]) - key) % 26]
        else:
            decrypted += text[i]
    return decrypted

text = "PROVACESAR123"
key = 3
encrypted = encrypt(text, key)
decrypted = decrypt(encrypted, key)
print(f"Encrypted text: {encrypted}")
print(f"Decrypted text: {decrypted}")

Encrypted text: SURYDFHVDU123
Decrypted text: PROVACESAR123


In [62]:
c = "VRBXQSHSLQLOOR"
for k in range(26):
    print(f"Key: {k} -> {decrypt(c, k)}")

print("\nProva encriptació amb clau correcta (3)")
print(encrypt("SOYUNPEPINILLO", 3))

Key: 0 -> VRBXQSHSLQLOOR
Key: 1 -> UQAWPRGRKPKNNQ
Key: 2 -> TPZVOQFQJOJMMP
Key: 3 -> SOYUNPEPINILLO
Key: 4 -> RNXTMODOHMHKKN
Key: 5 -> QMWSLNCNGLGJJM
Key: 6 -> PLVRKMBMFKFIIL
Key: 7 -> OKUQJLALEJEHHK
Key: 8 -> NJTPIKZKDIDGGJ
Key: 9 -> MISOHJYJCHCFFI
Key: 10 -> LHRNGIXIBGBEEH
Key: 11 -> KGQMFHWHAFADDG
Key: 12 -> JFPLEGVGZEZCCF
Key: 13 -> IEOKDFUFYDYBBE
Key: 14 -> HDNJCETEXCXAAD
Key: 15 -> GCMIBDSDWBWZZC
Key: 16 -> FBLHACRCVAVYYB
Key: 17 -> EAKGZBQBUZUXXA
Key: 18 -> DZJFYAPATYTWWZ
Key: 19 -> CYIEXZOZSXSVVY
Key: 20 -> BXHDWYNYRWRUUX
Key: 21 -> AWGCVXMXQVQTTW
Key: 22 -> ZVFBUWLWPUPSSV
Key: 23 -> YUEATVKVOTORRU
Key: 24 -> XTDZSUJUNSNQQT
Key: 25 -> WSCYRTITMRMPPS

Prova encriptació amb clau correcta (3)
VRBXQSHSLQLOOR


Comprovem, per cada key (k) de 0 a 25, quin és el missatge desxifrat. Veiem que amb key = 3, el missatge desxifrat és "SOYUNPEPINILLO". Provem a xifrar el missatge amb k=3 per a comprovar que és correcte.

**Resposta**: ha estat xifrat amb k=3.

### 2. If now the encrypted message is “EHFJEQZHEKTPEXH”, use the same program to find the worst time to find the original message. Can we find the k used? Is this cryptographic method secure?

In [63]:
c = "EHFJEQZHEKTPEXH"

for k in range(26):
    print(f"Key: {k} -> {decrypt(c, k)}")

Key: 0 -> EHFJEQZHEKTPEXH
Key: 1 -> DGEIDPYGDJSODWG
Key: 2 -> CFDHCOXFCIRNCVF
Key: 3 -> BECGBNWEBHQMBUE
Key: 4 -> ADBFAMVDAGPLATD
Key: 5 -> ZCAEZLUCZFOKZSC
Key: 6 -> YBZDYKTBYENJYRB
Key: 7 -> XAYCXJSAXDMIXQA
Key: 8 -> WZXBWIRZWCLHWPZ
Key: 9 -> VYWAVHQYVBKGVOY
Key: 10 -> UXVZUGPXUAJFUNX
Key: 11 -> TWUYTFOWTZIETMW
Key: 12 -> SVTXSENVSYHDSLV
Key: 13 -> RUSWRDMURXGCRKU
Key: 14 -> QTRVQCLTQWFBQJT
Key: 15 -> PSQUPBKSPVEAPIS
Key: 16 -> ORPTOAJROUDZOHR
Key: 17 -> NQOSNZIQNTCYNGQ
Key: 18 -> MPNRMYHPMSBXMFP
Key: 19 -> LOMQLXGOLRAWLEO
Key: 20 -> KNLPKWFNKQZVKDN
Key: 21 -> JMKOJVEMJPYUJCM
Key: 22 -> ILJNIUDLIOXTIBL
Key: 23 -> HKIMHTCKHNWSHAK
Key: 24 -> GJHLGSBJGMVRGZJ
Key: 25 -> FIGKFRAIFLUQFYI


Fent servir el mateix alfabet i iterant per cada key (k) de 0 a 25, no trobem un missatge desxifrat que tingui sentit. Si s'ha xifrat amb el mateix mètode, segurament s'ha fet servir un alfabet diferent. Així doncs, no podem trobar la key usada fins iterar per tots els alfabets possibles. Això fa que el mètode sigui segur, ja que no podem trobar la key usada tan fàcilment.

### 3. Supose that we have a cleartext where the relative frequency of the symbol “a” is 0.1. We also know that the digram “ny” appears with a frequency of 0.02.
- **(a) If we use a transposition cipher, will the letter “a” and the digram “ny” keep the same frequency
in the ciphertext?** Sí, els xifrats basats en transposició només alteren l'ordre dels caràcters, però no la seva identitat. Per tant, la freqüència de "a" es mantindrà igual. Quant al dígraf "ny", la seva freqüència global també es mantindrà, però és possible que els seus components quedin separats a causa de la reordenació.

- **(b) What happens if we use a simple or monoaphabetic substitution? Will the substituted symbols
keep the same frequency in both cases?** Sí, en aquest cas, cada lletra es reemplaça per un altre símbol fix, de manera que el nou símbol que substitueixi "a" tindrà exactament la mateixa freqüència que tenia "a" originalment. De la mateixa manera, el dígraf "ny" serà substituït per un altre parell de símbols, que mantindrà la mateixa freqüència que tenia "ny" en el text original. Això fa que els xifrats per substitució monoalfabètica siguin vulnerables a l'anàlisi de freqüència.

### 4. The Vigenère method is a polyalphabetic substituion cipher with a variable length key.

- We consider the key of length r as k = (k0, k1, . . . , kr−1)
- If the message M is greater than r, then the message is divided into blocks of size r. Given a
block of r symbols: m0, m1, . . . , mr−1, each symbol is encrypted as: ci = mi + ki (mod n) for
0 ≤ i ≤ r − 1, and n is the size of the alphabet.

Using the Vigenère cipher with the alphabet of size n = 26:

- **(a) If n = 26 and r = 5, what is the size of the key space?** Per definició, el nombre de claus possibles és n^r, on n és la mida de l'alfabet i r és la longitud de la clau. En aquest cas, n = 26 i r = 5, de manera que el nombre de claus possibles és 26^5 = 11.881.376.
- **(b) Encrypt the message “VOLANDO VOY VOLANDO VENGO” (without spaces) with the key “CAMARON” using the Vigenère cipher and the previous alphabet of size n = 26.**

In [64]:
m = "VOLANDOVOYVOLANDOVENGO"
k = "CAMARON"

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

def vigenere(text: str, key: str) -> str:
    text = text.upper()
    key = key.upper()
    encrypted = ""
    key_length = len(key)
    
    for i in range(len(text)):
        if text[i] in alphabet:
            text_index = alphabet.index(text[i])
            key_index = alphabet.index(key[i % key_length])
            encrypted_index = (text_index + key_index) % 26
            encrypted += alphabet[encrypted_index]
        else:
            encrypted += text[i]
    
    return encrypted

def devigenere(text: str, key: str) -> str:
    text = text.upper()
    key = key.upper()
    decrypted = ""
    key_length = len(key)
    
    for i in range(len(text)):
        if text[i] in alphabet:
            text_index = alphabet.index(text[i])
            key_index = alphabet.index(key[i % key_length])
            decrypted_index = (text_index - key_index) % 26
            decrypted += alphabet[decrypted_index]
        else:
            decrypted += text[i]
    
    return decrypted

encrypted = vigenere(m, k)
decrypted = devigenere(encrypted, k)
print(f"Encrypted text: {encrypted}")
print(f"Decrypted text: {decrypted}")

Encrypted text: XOXAERBXOKVFZNPDAVVBTQ
Decrypted text: VOLANDOVOYVOLANDOVENGO


- **(c) We know that the cleartext “COMELVALLESNOHIHARES” has been encrypted as the ciphertext “OCXEXJLLXSDNAVTHMFPS”. We also know that the key length is r = 4. Can you find the key?**

In [65]:
m = "COMELVALLESNOHIHARES"
c = "OCXEXJLLXSDNAVTHMFPS"

distances = []

for i in range(4):
    dist = alphabet.index(c[i]) - alphabet.index(m[i])
    if dist < 0:
        dist += 26
    distances.append(dist)

key = "".join([alphabet[d] for d in distances])

print(f"Key: {key}")

print(f"Decrypted text: {devigenere(c, key)}")

Key: MOLA
Decrypted text: COMELVALLESNOHIHARES


### 5. Hill cipher:

As an example, we have the alphabet with 26 symbols, so n = 26 and the key:
K = [[2 18 3]
    [5 7 11]
    [9 14 20]]

- **(a) Encrypt the message “BARCELONA” using the Hill cipher with the same key K as the previous example.**

In [66]:
import numpy as np

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

def str_to_matrix(text: str, n: int) -> np.array:
    # Afegim padding al text per fer que la seva longitud sigui múltiple de n
    while len(text) % n != 0:
        text += 'X'  # Utilitzem 'X' com a caràcter de padding
    return np.array([[alphabet.index(c) for c in text[i:i+n]] for i in range(0, len(text), n)])

def matrix_to_str(matrix: np.array) -> str:
    return "".join([alphabet[int(matrix[i][j]) % 26] for i in range(matrix.shape[0]) for j in range(matrix.shape[1])])

m = "BARCELONA"
key = np.array([[2, 18, 3], [5, 7, 11], [9, 14, 20]])

# Comprovem k inversa:
det = np.linalg.det(key)
# det = -25 --> != 0 --> existeix inversa

key_inv = np.linalg.inv(key) * det
key_inv = np.round(key_inv).astype(int) % 26

m_matrix = str_to_matrix(m, key.shape[0])

print(f"Matriu del missatge (m_matrix):\n{m_matrix}\n")

print(f"Clau (key):\n{key}\n")

c_matrix = np.dot(m_matrix, key.T) % 26

print(f"Multiplicació de matrius per encriptar (m_matrix * key.T):\n{c_matrix}\n")

c = matrix_to_str(c_matrix)
print(f"Text encriptat: {c}\n")

print(f"Clau inversa (key_inv):\n{key_inv}\n")

m_matrix_decrypted = np.dot(c_matrix, key_inv.T) % 26

print(f"Multiplicació de matrius per desencriptar (c_matrix * key_inv.T):\n{m_matrix_decrypted}\n")

m_decrypted = matrix_to_str(m_matrix_decrypted)
print(f"Text desencriptat: {m_decrypted}")


Matriu del missatge (m_matrix):
[[ 1  0 17]
 [ 2  4 11]
 [14 13  0]]

Clau (key):
[[ 2 18  3]
 [ 5  7 11]
 [ 9 14 20]]

Multiplicació de matrius per encriptar (m_matrix * key.T):
[[ 1 10 11]
 [ 5  3  8]
 [ 2  5 22]]

Text encriptat: BKLFDICFW

Clau inversa (key_inv):
[[12 20 21]
 [25 13 19]
 [ 7  4  2]]

Multiplicació de matrius per desencriptar (c_matrix * key_inv.T):
[[ 1  0 17]
 [ 2  4 11]
 [14 13  0]]

Text desencriptat: BARCELONA


- **(b) Using also the same key, can you decrypt the message “XELOEKSVVRQXAMQSZIEGCMGSULBYZYQDRKYEQKKUQEIEH”? (note: you need to compute K−1)**

In [67]:
c = "XELOEKSVVRQXAMQSZIEGCMGSULBYZYQDRKYEQKKUQEIEH"
c_matrix = str_to_matrix(c, key.shape[0])

print(f"Clau inversa (key_inv):\n{key_inv}\n")

m_matrix_decrypted = np.dot(c_matrix, key_inv.T) % 26

print(f"Multiplicació de matrius per desencriptar (c_matrix * key_inv.T):\n{m_matrix_decrypted}\n")

m_decrypted = matrix_to_str(m_matrix_decrypted)
print(f"Text desencriptat: {m_decrypted}")

Clau inversa (key_inv):
[[12 20 21]
 [25 13 19]
 [ 7  4  2]]

Multiplicació de matrius per desencriptar (c_matrix * key_inv.T):
[[15  4 17]
 [16 20  4]
 [11  4 18]
 [19  4 21]
 [ 4 18  2]
 [ 0 17  8]
 [ 2  8  4]
 [18 18 14]
 [13 12  4]
 [18  3  4]
 [11  8  2]
 [ 8 14 18]
 [ 4 18 16]
 [20  4  4]
 [11 21  8]]

Text desencriptat: PERQUELESTEVESCARICIESSONMESDELICIOSESQUEELVI


**Text desencriptat (amb espais): "PERQUE LES TEVES CARICIES SON MES DELICIOSES QUE EL VI"**

### 6. In a Hill cipher using matrices, Alice wants to use the key “POOL” while Bob wants to use “SWIM”. Who should we trust?

In [68]:
import numpy as np

def str_to_matrix(text: str, n: int) -> np.array:
    return np.array([[alphabet.index(c) for c in text[i:i+n]] for i in range(0, len(text), n)])

def mod_inverse(a, m):
    # trobar inversa modular
    for x in range(1, m):
        if (a * x) % m == 1:
            return x
    return None

key1 = "POOL"
key2 = "SWIM"

key1_matrix = str_to_matrix(key1, 2)
key2_matrix = str_to_matrix(key2, 2)

det1 = int(np.round(np.linalg.det(key1_matrix))) % 26
det2 = int(np.round(np.linalg.det(key2_matrix))) % 26

inv_det1 = mod_inverse(det1, 26)
inv_det2 = mod_inverse(det2, 26)

print(f"Clau 'POOL': \n{key1_matrix} --> det = {det1}, inversa = {inv_det1}")

if inv_det1 is not None:
    print("La clau 'POOL' és vàlida.")
else:
    print("La clau 'POOL' no és vàlida.")

print(f"\nClau 'SWIM': \n{key2_matrix} --> det = {det2}, inversa = {inv_det2}")

if inv_det2 is not None:
    print("La clau 'SWIM' és vàlida.")
else:
    print("La clau 'SWIM' no és vàlida.")

Clau 'POOL': 
[[15 14]
 [14 11]] --> det = 21, inversa = 5
La clau 'POOL' és vàlida.

Clau 'SWIM': 
[[18 22]
 [ 8 12]] --> det = 14, inversa = None
La clau 'SWIM' no és vàlida.


Veiem que els determinants de la clau "POOL" i "SWIM" no són 0. Això no confirma que siguin claus vàlides, i per això hem de trobar la inversa modular de la matriu, és a dir, validar si, amb modul 26, la matriu és invertible. Si una matriu no és invertible, no es pot fer servir per a desxifrar. En aquest cas, la clau "POOL" és vàlida, mentre que la clau "SWIM" no ho és. Per tant, hem de confiar en **Alice**.