# Practica 4: Codificació i Descodificació de cadenes de text

A la sessio anterior hem programat mitjançant codis de Hamming la codificacio i descodificacio de vectors i matrius. En aquesta sessió, posarem a prova de codificar i descodificar missatges amb el codi ASCII transformant
prèviament en codi binari.

Familiaritzeu-vos amb les següents variables, que són, el codi  $𝐶$ i la seva matriu de control  $𝐻$.

Aquesta informació serà els vostres paràmetres de cadascuna de les funcions que us demanarem que implementeu per aquesta sessió de pràctica.

**𝑁𝑜𝑡𝑎 :** Recordeu que les cel·les de la llibreta Jupiter tenen memòria, és a dir, que cel·les executades posteriorment, tenen definides les variables de les cel·les anteriors.

In [1]:
import numpy as np
import math

H = np.matrix([(1, 1, 0, 1, 1, 0, 0), (1, 1, 1, 0, 0, 1, 0), (1, 0, 1, 1, 0, 0, 1)]) 
C = np.matrix([
    (0, 0, 0, 0, 0, 0, 0), 
    (0, 0, 0, 1, 1, 0, 1),            
    (0, 0, 1, 0, 0, 1, 1),
    (0, 0, 1, 1, 1, 1, 0),
    (0, 1, 0, 0, 1, 1, 0),
    (0, 1, 0, 1, 0, 1, 1),
    (0, 1, 1, 0, 1, 0, 1),
    (0, 1, 1, 1, 0, 0, 0),
    (1, 0, 0, 0, 1, 1, 1),
    (1, 0, 0, 1, 0, 1, 0),
    (1, 0, 1, 0, 1, 0, 0),
    (1, 0, 1, 1, 0, 0, 1),
    (1, 1, 0, 0, 0, 0, 1),
    (1, 1, 0, 1, 1, 0, 0),
    (1, 1, 1, 0, 0, 1, 0),
    (1, 1, 1, 1, 1, 1, 1)])

**1.** Conversio d’un missatge de text a seqüència binària, i viceversa. 

Per codificar i descodificar una cadena de text, necessitarem convertir una cadena de text a una seqüència binària, i viceversa.

**(a)** Dissenyeu la funció $StringToBinarySeq(sStr)$ que, donada una cadena de text $sStr$ de longitud $n$, retorni:

(i) Una llista de longitud $n$ amb el codi ASCII representat amb nombres decimals dels caràcters de $sStr$.

(ii) Una llista de longitud 8n amb els bits obtinguts a la llista anterior.

Per exemple, $StringToBinarySeq(”mi”)$ ha de retornar: [109,105],[0,1,1,0,1,1,0,1,0,1,1,0,1,0,0,1].

Nota: Podeu aprofitar els següents exemples:

- " ".join("informacio") => "i n f o r m a c i o"
- "{0:03b}".format(5) => "101"

In [2]:
import numpy as np

def StringToBinary(sStr):
    ll_bin=[]
    ll_ascii=[ord(i) for i in sStr]
    for n in ll_ascii:
        binari="{0:08b}".format(n)
        ll_bin.append(binari)
    ll_bin=''.join(ll_bin)
    ll_bin=[int(x) for x in ll_bin]
    return ll_ascii,ll_bin


**(b)** Considereu la cadena de text "Codi". Executeu $StringToBinarySeq(s)$ i mostreu els resultats.


In [3]:
ascii,bina=StringToBinary("Codi")
print(ascii)
print(bina)

[67, 111, 100, 105]
[0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1]


**(c)** Dissenyeu la funció $BinarySeqToString(sBin)$ que realitzi el proces contrari a la funció anterior, o  sigui, que donada una seqüència binària sBin, retorni:

(i)Una llista amb el codi ASCII representat amb nombres decimals.

(ii)La cadena de text corresponent.

Nota: 

- Busqueu a Internet com funciona np.split()

- Per convertir en base 10 un número binari, int(binari, 2)


In [4]:
import numpy as np

def BinaryToString(sBin):
    binary_str = ''.join(str(bit) for bit in sBin)
    bytes_arr = np.array([binary_str[i:i+8] for i in range(0, len(binary_str), 8)])
    string = ''.join(chr(int(byte, 2)) for byte in bytes_arr)
    return string

**(d)** Utilitzeu la funció $BinarySeqToString(sBin)$ implementada anteriorment. Recupereu la cadena de text corresponent a la seqüència binària $sBin$ obtinguda en l’apartat **1(b)**, juntament amb la cadena corresponent.

In [5]:
string=BinaryToString(bina)
print(string)

Codi


**2.** Codificació i descodificació de text. 

Feu servir principalment les funcions per codificar i descodificar de la sessió anterior, així com totes les funcions que cregueu oportunes d’aquella sessió, les funcions de conversió de l’apartat 1, i les funcions $VectorToMatrix$ i $MatrixToVector$. Considereu sempre el codi de Hamming amb paràmetre r = 3 amb la matriu de control donada a **(1)**.

In [33]:
import numpy as np

def longitudCodiHamming(r):
    n=(2**r)-1
    return n

def dimensioCodiHamming(r):
    n=longitudCodiHamming(r)
    k=n-r
    return k

def distanciaCodiHamming():
    return 3
    
    
#Càlcul de la matriu G
def matriu_generadora(H):
    r=3
    files=H.shape[1]-H.shape[0]
    matriu=H[:,:-r]
    transposada=np.transpose(matriu)
    identidad = np.identity(files)
    generadora = np.hstack((identidad, transposada))
    return generadora

def CodificaHamming(G, m):
    codificat=(m*G)%2
    return codificat

def DescodificaHamming(H, w):
    dimensio=dimensioCodiHamming(3)
    longitud=longitudCodiHamming(3)
    sindrome=(w*H.transpose())%2
    error=np.zeros((1,longitud))
    pos=0
    for fila in H.transpose():
        if fila.tolist()==sindrome.tolist():
            error[0][pos]=1
        pos+=1
    corregit=(error+w)%2
    info=corregit[:, :dimensio].tolist()
    return sindrome, corregit, info

def VectorToMatrix(vec,n):
    Arr=[]
    Arr = np.split(vec,n)
    Mat = np.matrix(Arr)
    return Mat

def MatrixToVector(mat):
    v = np.array(mat)
    v = v.flatten()
    v = v.astype(int)
    return v

**(a)** Codifiqueu la cadena de text de l'apartat **1(b)** i mostra, la matriu sense codificar i la matriu codificada.

In [34]:
ascii,bina=StringToBinary("Codi")
bina=np.array(bina)
matriu_no_codificada = VectorToMatrix(bina, 8)
G = matriu_generadora(H)
matriu_codificada = CodificaHamming(G, matriu_no_codificada)
print("Matriu sense codificar: ", matriu_no_codificada)
print("Matriu codificada:", matriu_codificada)

Matriu sense codificar:  [[0 1 0 0]
 [0 0 1 1]
 [0 1 1 0]
 [1 1 1 1]
 [0 1 1 0]
 [0 1 0 0]
 [0 1 1 0]
 [1 0 0 1]]
Matriu codificada: [[0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 0. 1. 0. 1.]
 [0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 1. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0. 1. 0.]]


**(b)** Descodifica el resultat de l'apartat **2(a)** i mostra la cadena de text.

In [35]:
sindrome, corregit, info = DescodificaHamming(H, matriu_codificada)
matriu=MatrixToVector(info)
string=BinaryToString(matriu)
print("Cadena de text: ", string)


Cadena de text:  Codi
[[0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0], [0.0, 1.0, 1.0, 0.0], [1.0, 1.0, 1.0, 1.0], [0.0, 1.0, 1.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0], [1.0, 0.0, 0.0, 1.0]]


**(c)** Quin es el nombre máxim d’errors que es poden introduir a la matriu codificada de manera que es puguin corregir? A quines posicions podem afegir aquests errors? La funció $AfegirErrors(M,f,c)$, on els paràmetres són una matriu $M$, una fila $f$ i una columna $c$, introdueix un error a $M$ a la posició $(f, c)$. Feu servir la funció $AfegirErrors(M,f,c)$ per afegir els errors i comproveu llavors que, afegint aquests errors, la cadena de l’apartat 1(b) segueix sent la mateixa un cop descodificada.

In [37]:
def AfegeixErrors(M,f,c):
    M[f,c] =  (M[f,c] + 1) %2
     
    return M

In [46]:
import math
d=distanciaCodiHamming()
max_errors=math.floor((d-1)/2)
print("El maxim d'errors que es pot corregir", max_errors)

El maxim d'errors que es pot corregir 1


In [65]:
matriu_codificada=CodificaHamming(G, matriu_no_codificada)
matriu_codificada=AfegeixErrors(matriu_codificada,2,5)


sindrome, corregit, info = DescodificaHamming(H, matriu_codificada)
matriu=MatrixToVector(info)
string=BinaryToString(matriu)
print("Cadena de text: ", string)

Cadena de text:  Codi


**Resposta:** El maxim d'errors que es pot corregir 1 ja que la matriu de control és 1-correctora (perquè si r=3, (r-1)/2=1). Les posicions on podem afegir aquests errors són aquelles que no formin part de les 4 primeres columnes, ja que és on es troba la informació.

**(d)** Quin és nombre mínim d’errors que es poden introduir a la matriu codificada de manera que no es puguin corregir? A quines posicions podem afegir aquests errors? Utilitzeu la funció $AfegirErrors(M,f,c)$ per
afegir els errors i comproveu llavors que, afegint aquests errors, la cadena de l’apartat 1 (b) no és la mateixa un cop descodificada.

In [67]:
matriu_codificada=CodificaHamming(G, matriu_no_codificada)
matriu_codificada=AfegeixErrors(matriu_codificada,4,3)


sindrome, corregit, info = DescodificaHamming(H, matriu_codificada)
matriu=MatrixToVector(info)
string=BinaryToString(matriu)
print("Cadena de text: ", string)

Cadena de text:  Coti


**Resposta:** La matriu de control és 1-correctora (perquè si r=3, (r-1)/2=1), per tant com mínim podrem afegir 1 error sempre que no el situem en alguna posició que es trobi en el 4 primeres columnes (on es troba la informació), si posem un error en alguna de les primeres 4 columnes, no es podrà corregir i la cadena de text canviarà.