# Practica 4: Codificació i Descodificació de cadenes de text

A la sessio anterior hem programat mitjançant codis de Hamming la codificacio i descodificacio de vectors i matrius. En aquesta sessió, posarem a prova de codificar i descodificar missatges amb el codi ASCII transformant
prèviament en codi binari.

Familiaritzeu-vos amb les següents variables, que són, el codi  $𝐶$ i la seva matriu de control  $𝐻$.

Aquesta informació serà els vostres paràmetres de cadascuna de les funcions que us demanarem que implementeu per aquesta sessió de pràctica.

**𝑁𝑜𝑡𝑎 :** Recordeu que les cel·les de la llibreta Jupiter tenen memòria, és a dir, que cel·les executades posteriorment, tenen definides les variables de les cel·les anteriors.

In [25]:
import numpy as np
import math


H = np.matrix([(1, 1, 0, 1, 1, 0, 0), (1, 1, 1, 0, 0, 1, 0), (1, 0, 1, 1, 0, 0, 1)]) 
C = np.matrix([
    (0, 0, 0, 0, 0, 0, 0), 
    (0, 0, 0, 1, 1, 0, 1),            
    (0, 0, 1, 0, 0, 1, 1),
    (0, 0, 1, 1, 1, 1, 0),
    (0, 1, 0, 0, 1, 1, 0),
    (0, 1, 0, 1, 0, 1, 1),
    (0, 1, 1, 0, 1, 0, 1),
    (0, 1, 1, 1, 0, 0, 0),
    (1, 0, 0, 0, 1, 1, 1),
    (1, 0, 0, 1, 0, 1, 0),
    (1, 0, 1, 0, 1, 0, 0),
    (1, 0, 1, 1, 0, 0, 1),
    (1, 1, 0, 0, 0, 0, 1),
    (1, 1, 0, 1, 1, 0, 0),
    (1, 1, 1, 0, 0, 1, 0),
    (1, 1, 1, 1, 1, 1, 1)])

**1.** Conversio d’un missatge de text a seqüència binària, i viceversa. 

Per codificar i descodificar una cadena de text, necessitarem convertir una cadena de text a una seqüència binària, i viceversa.

**(a)** Dissenyeu la funció $StringToBinarySeq(sStr)$ que, donada una cadena de text $sStr$ de longitud $n$, retorni:

(i) Una llista de longitud $n$ amb el codi ASCII representat amb nombres decimals dels caràcters de $sStr$.

(ii) Una llista de longitud 8n amb els bits obtinguts a la llista anterior.

Per exemple, $StringToBinarySeq(”mi”)$ ha de retornar: [109,105],[0,1,1,0,1,1,0,1,0,1,1,0,1,0,0,1].

Nota: Podeu aprofitar els següents exemples:

- " ".join("informacio") => "i n f o r m a c i o"
- "{0:03b}".format(5) => "101"

In [26]:
def StringToBinarySeq(sStr):
    binary_list=[] #Creem la llista on es guardarà la seqüència binària
    ascii_list=[ord(char) for char in sStr] #Convertim cada caràcter de sStr a ASCII
    
    for n in ascii_list: #Per cada número ASCII el convertim a binàri i l'afegim a la llista creada al principi
        binary="{0:08b}".format(n)
        binary_list.append(binary)

    binary_list=''.join(binary_list) #Agrupem els valors
    binary_list=[int(digit) for digit in binary_list] #Convertim els números a enters 
    
    return ascii_list, binary_list #Retornem les dues llistes

**(b)** Considereu la cadena de text "Codi". Executeu $StringToBinarySeq(s)$ i mostreu els resultats.


In [27]:
#Cridem a la funció i visualitzem el resultat
ascii,binary=StringToBinarySeq("Codi")

print("ASCII:",ascii)
print("Cadena binària:",binary)

ASCII: [67, 111, 100, 105]
Cadena binària: [0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1]


**(c)** Dissenyeu la funció $BinarySeqToString(sBin)$ que realitzi el proces contrari a la funció anterior, o  sigui, que donada una seqüència binària sBin, retorni:

(i)Una llista amb el codi ASCII representat amb nombres decimals.

(ii)La cadena de text corresponent.

Nota: 

- Busqueu a Internet com funciona np.split()

- Per convertir en base 10 un número binari, int(binari, 2)


In [28]:
def BinarySeqToString(sBin):
    binary_seq = ''.join(str(bit) for bit in sBin) #Creem la seqüència binària
    bits_array = np.array([binary_seq[i:i+8] for i in range(0, len(binary_seq), 8)]) #Agrupem en grups de 8 bits perquè és el que ocupa cada caràcter
    res = ''.join(chr(int(bits, 2)) for bits in bits_array) #Convertim a base 10 cada grup d'1 byte i agrupem els resultats per formar la cadena

    return res

**(d)** Utilitzeu la funció $BinarySeqToString(sBin)$ implementada anteriorment. Recupereu la cadena de text corresponent a la seqüència binària $sBin$ obtinguda en l’apartat **1(b)**, juntament amb la cadena corresponent.

In [29]:
#Visualitzem la cadena de text a partir de la seqüència binària de l'apartat 1(b)
print(BinarySeqToString(binary))

Codi


**2.** Codificació i descodificació de text. 

Feu servir principalment les funcions per codificar i descodificar de la sessió anterior, així com totes les funcions que cregueu oportunes d’aquella sessió, les funcions de conversió de l’apartat 1, i les funcions $VectorToMatrix$ i $MatrixToVector$. Considereu sempre el codi de Hamming amb paràmetre r = 3 amb la matriu de control donada a **(1)**.

In [30]:
def longitudCodiHamming(r):
    return (2**r)-1

def dimensioCodiHamming(r):
    n=longitudCodiHamming(r)
    return n-r

def distanciaCodiHamming():
    return 3
    
#Càlcul de la matriu G
def calcula_generadora(H):
    P_transposed = H[:,:H.shape[1]-H.shape[0]]
    identitat = np.identity(H.shape[1] - H.shape[0], dtype = "int")
    G = np.concatenate((identitat,-np.transpose(P_transposed)), axis = 1)
    
    return G

#Agafat de la pràctica anterior
def CodificaHamming(G, v):
    codif=(v*G)%2
    
    return codif


def DescodificaHamming(H, w):

    i =0
    dim =dimensioCodiHamming(3)
    len =longitudCodiHamming(3)
    sin =(w*H.transpose())%2
    corregir =np.zeros((1,len))


    for fila in H.transpose():
        if fila.tolist()==sin.tolist():
            corregir[0][i]=1

        i+=1

    correcte =(corregir+w)%2
    informacio =correcte[:, :dim].tolist()
    
    return sin, correcte, informacio

def VectorToMatrix(vec,n):
    Arr=[]
    Arr = np.split(vec,n)
    Mat = np.matrix(Arr)
    return Mat

def MatrixToVector(mat):
    v = np.array(mat)
    v = v.flatten()
    v = v.astype(int)
    return v

**(a)** Codifiqueu la cadena de text de l'apartat **1(b)** i mostra, la matriu sense codificar i la matriu codificada.

In [31]:
#Obtenim el binari de la paraula "Codi" i creem la matriu associada
ascii,binary=StringToBinarySeq("Codi")
matriu_ncodif = VectorToMatrix(np.array(binary), 8)

#Codifiquem la matriu associada amb la generadora i visualitzem els resultats
G = calcula_generadora(H)
matriu_codif = CodificaHamming(G, matriu_ncodif)
print("Matriu sense codificar:\n ", matriu_ncodif)
print("Matriu codificada:\n", matriu_codif)

Matriu sense codificar:
  [[0 1 0 0]
 [0 0 1 1]
 [0 1 1 0]
 [1 1 1 1]
 [0 1 1 0]
 [0 1 0 0]
 [0 1 1 0]
 [1 0 0 1]]
Matriu codificada:
 [[0 1 0 0 1 1 0]
 [0 0 1 1 1 1 0]
 [0 1 1 0 1 0 1]
 [1 1 1 1 1 1 1]
 [0 1 1 0 1 0 1]
 [0 1 0 0 1 1 0]
 [0 1 1 0 1 0 1]
 [1 0 0 1 0 1 0]]


**(b)** Descodifica el resultat de l'apartat **2(a)** i mostra la cadena de text.

In [32]:
#Descodifiquem i visualitzem el string resultant
sin, correcio, informacio = DescodificaHamming(H, matriu_codif)
matriu =MatrixToVector(informacio)
res =BinarySeqToString(matriu)
print("Text: ", res)


Text:  Codi







**(c)** Quin es el nombre máxim d’errors que es poden introduir a la matriu codificada de manera que es puguin corregir? A quines posicions podem afegir aquests errors? La funció $AfegirErrors(M,f,c)$, on els paràmetres són una matriu $M$, una fila $f$ i una columna $c$, introdueix un error a $M$ a la posició $(f, c)$. Feu servir la funció $AfegirErrors(M,f,c)$ per afegir els errors i comproveu llavors que, afegint aquests errors, la cadena de l’apartat 1(b) segueix sent la mateixa un cop descodificada.

In [33]:
def AfegeixErrors(M,f,c):
    M[f,c] =  (M[f,c] + 1) %2
     
    return M

In [34]:
#Apliquem la fórmula explicada a classe ((d-1)/2)
distance =distanciaCodiHamming()
n_errors = round((distance-1)/2)

print("Nombre d'errors màxims que permeten corregir la matriu:", n_errors)

Nombre d'errors màxims que permeten corregir la matriu: 1


In [35]:
#Afegim error a una de les ultimes columnes 
codif_mat=CodificaHamming(G, matriu_ncodif)
matriu_codificada=AfegeixErrors(codif_mat,5,6)

#Descodifiquem i visualitzem el resultat
sin, correcio, informacio = DescodificaHamming(H, matriu_codificada)
mat =MatrixToVector(informacio)
res =BinarySeqToString(mat)

print("Text: ", res)

Text:  Codi


**Resposta:** La quantitat màxima d'errors que es poden corregir és 1. Això és degut a la naturalesa de la matriu de control, que és 1-correcció. Quan el paràmetre r=3, el màxim d'errors corregibles és (r-1)/2, cosa que dóna com a resultat 1. Només podem afegir errors en posicions posteriors a la quarta columna, ja que és on es conté la informació. S'observa que el resultat "Codi" coincideix amb l'original.

**(d)** Quin és nombre mínim d’errors que es poden introduir a la matriu codificada de manera que no es puguin corregir? A quines posicions podem afegir aquests errors? Utilitzeu la funció $AfegirErrors(M,f,c)$ per
afegir els errors i comproveu llavors que, afegint aquests errors, la cadena de l’apartat 1 (b) no és la mateixa un cop descodificada.

In [36]:
#Afegim error a la 4rta columna (4 primeres)
matriu_codificada = CodificaHamming(G, matriu_ncodif)
matriu_codificada = AfegeixErrors(matriu_codificada,5,3)

#Descodifiquem i visualitzem el resultat
sin, correcio, informacio = DescodificaHamming(H, matriu_codificada)
mat = MatrixToVector(informacio)
res = BinarySeqToString(mat)

print("Text: ", res)

Text:  Coei


**Resposta:** Tal com s'ha explicat a l'anterior apartat, la naturalesa de la matriu de control és d'1-correció (també 2-detectora). Per tant, sempre podrem aplicar com a mínim 1 error degut a la fórmula (r-1)/2 = 1. Pel que fa a les posicions, l'anterior afirmació només es cumplirà mentres l'error no s'afegeixi a una posició de les primeres 4 columnes. Tal com s'osberva a l'exemple hem modificat una de les 4 primeres columnes i ens ha retornat com a resultat "Coei" != "Codi".