# Practica 3 - Numpy Ajuda


Aquesta plantilla de Jupyter us proporciona una serie d'exemple del us més habitual de Numpy que us servirà per la realització de la pràctica.

És important que practiqueu una mica a través d'aquesta llibreta per no sentir-vos bloquejats en la pràctica!


### Creació de Arrays i Operacions

In [1]:
import numpy as np # Importem el paquet de numpy, i li donem un alias

# Creem un array a traves de donar valors a traves d'una llista
# de Python
A = np.array([1,2,3])
print(A)

B = np.array([i+1 for i in range(3)])
print(B)

# Numpy utilitza per defecte el que es coneix com "element-wise" 
# a l'hora de fer operacions en els np.array() i els np.matrix(); es a dir, 
# va element per element en element amb aquest tipus de dades

print('La suma del vector A i B resulta un altre vector: ', A+B)

# Tant mateix, per la operacio multiplicacio, aixo difereix una mica

# Pels np.array([]), la multiplicacio actua com element-wise.
# mentre que per np.matrix([]), en fa una multiplcacio de matrius
# com les que coneixem (ho veurem mes endavant)

print('La multiplicacio del vector A i B resulta: ', A*B)
print('La multiplicacio del vector A i B.transpose(): ', A*B.transpose())

print('La mida de A es ', len(A), ' o ', A.shape[0])
print('El fet que A no te una segona dimensio, aixo, no funciona: ')

try: 
    soc_un_numero_impossible = A.shape[1]
except Exception as e:
    print('S'' ha produit un error...', e)

   

[1 2 3]
[1 2 3]
La suma del vector A i B resulta un altre vector:  [2 4 6]
La multiplicacio del vector A i B resulta:  [1 4 9]
La multiplicacio del vector A i B.transpose():  [1 4 9]
La mida de A es  3  o  3
El fet que A no te una segona dimensio, aixo, no funciona: 
S ha produit un error... tuple index out of range


### Slicing Numpy Arrays

In [2]:
# Igual que amb les llistes de Python, podem fer
# 'slicing' amb arrays/matrius de numpy

C = np.array([i+1 for i in range(15)])
print(C)

# [baix:alt:salt]
# Si poso 'baix', em mostrara totes les opcions desde baix->final array
# Si poso 'alt', em mostrara totes les opcions desde inici array->alt
print('Els primers 5 numeros de C ', C[:5])
print('Els ultims 5 numeros de C ', C[-5:])

# El fet que tenim una sola dimensio, doncs, np.array funcionen
# de la mateixa manera que les llistes de python a l'hora de fer slicing



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Els primers 5 numeros de C  [1 2 3 4 5]
Els ultims 5 numeros de C  [11 12 13 14 15]


## Creacio de Matrius i operacions

In [3]:
# Crear matrius

# Una matriu amb tres files, i 2 columnes (dos elements per llista, amb tres llistes)
F3 = np.matrix([[1, 2], [3, 4], [4, 5]])
print(F3, F3.shape)

# Una matriu amb dos files, i 3 columnes:
C3 = np.matrix([[1, 2, 3], [5, 6, 7]])
print(C3, C3.shape)

print('La matriu C3 te ', C3.shape[0], ' files i ', C3.shape[1], ' cols')

# np.matrix(), a diferencia dels arrays, la multiplicacio no es
# element-wise

R = F3*C3
print('El resultat de la multiplicacio es:', R)

try:
    print('Intentant multiplicar amb ', F1.shape, ' i ', C1.transpose().shape, ' mides...')
    soc_una_matriu_impossible = F1*C1.transpose()
except Exception as e:
    print('S'' ha produit un error...', e) 

    
F1 = np.matrix([[1, 2, 3]])
C1 = np.matrix([[1], [2], [3]])
    
# Pero les altres operacions, com la suma, inclus amb matrius, son element-wise
print('L''operacio + entre dos matrius: ', F1 + C1, ' amb mida: ',(F1+C1).shape)

print('Pero esta clar que no podem fer operacions element-wise amb totes les matrius')
print('Amb F3 mida ', F3.shape, ' i C3 mida ', C3.shape)
try:
    print(F3 + C3)
except Exception as e:
    print('No s''ha pogut sumar dos matrius per: ', e)

# I aixo inclou... a les operacions de comparacio:
print('L''operacio == entre dos matrius: ', F1 == C1, ' amb mida ', (F1 == C1).shape)
    
    
# De manera que si aixo ho posem dins de un if..., Python no sap que fer!:
try:
    if F1 == C1:
        print('Son iguals?')
    else:
        print('Son diferents?')
except Exception as e:
    print('No se si son iguals o diferents!!!: ', e)
    
    
# Com podem determinar si una MATRIU es igual a UN ALTRE?

# Doncs tenim dos maneres... 

# Si llegim l'error, ens suggereix aquesta :) ->
if (F1 == C1).all():
    print('Les dues matrius son iguals, sense cap dubte!')
else:
    print('Les dues matrius son diferents, sense cap dubte!')

# O be, utilitzant funcions de Numpy:
if np.array_equal(F1, C1):
    print('Les dues matrius son iguals, amb arrays_equals!')
else:
    print('Les dues matrius son diferents, amb arrays_equals!')

    
    
print("Com ajuntem dues matrius? De manera horitzontal podem fer: ")
print(np.hstack((F1.transpose(), C1)))

print("O, les podem ajuntar de manera vertical: ")
print(np.vstack((F1.transpose(), C1)))
    


[[1 2]
 [3 4]
 [4 5]] (3, 2)
[[1 2 3]
 [5 6 7]] (2, 3)
La matriu C3 te  2  files i  3  cols
El resultat de la multiplicacio es: [[11 14 17]
 [23 30 37]
 [29 38 47]]
S ha produit un error... name 'F1' is not defined
Loperacio + entre dos matrius:  [[2 3 4]
 [3 4 5]
 [4 5 6]]  amb mida:  (3, 3)
Pero esta clar que no podem fer operacions element-wise amb totes les matrius
Amb F3 mida  (3, 2)  i C3 mida  (2, 3)
No sha pogut sumar dos matrius per:  operands could not be broadcast together with shapes (3,2) (2,3) 
Loperacio == entre dos matrius:  [[ True False False]
 [False  True False]
 [False False  True]]  amb mida  (3, 3)
No se si son iguals o diferents!!!:  The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Les dues matrius son diferents, sense cap dubte!
Les dues matrius son diferents, amb arrays_equals!
Com ajuntem dues matrius? De manera horitzontal podem fer: 
[[1 1]
 [2 2]
 [3 3]]
O, les podem ajuntar de manera vertical: 
[[1]
 [2]
 [3]
 [1

## Slicing amb Matrius

In [4]:
from random import randint, seed
# El fet que ara estem introduint una nova dimensio... l'indexacio
# amb elles es menys intuitiva

D = np.identity(5)
D = np.matrix( [[1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10], 
    [11, 12, 13, 14, 5], 
    [16, 17, 0, 19, 5],
    [20, 21, 22, 23, 24]])
print(D)

print('Primera fila: ', D[0,:])
print('Primera columna: ', D[:,0])

print('Tres primeres files, i dos primeres columnes ')
print(D[0:3, 0:2])

print('Quants elements no-zeros hi han a la quarta fila?', np.count_nonzero(D[3,:]))


# Recorda que... False = 0, True = 1, i que les operacions condicionals son aplicades per element...
print('Quants elements diferents a 5 hi han a la cinquena columna?', np.count_nonzero(D[:, 4] != 5))

for c in D[:,4]:
    print('L\'element ', c, ' de la cinquena columna es diferent a 5 : ', c != 5)


for r in range(D.shape[0]):
    print('A la fila ', r, ' hi tenim ', D[r,:], ' amb ', np.count_nonzero(D[r,:]), ' numeros de zeros')

    
# Loop per buscar una fila en concret...
a_comparar = np.matrix([11, 12, 13, 14, 5]) 
n = D.shape[0] # Quantes files tenim?
posicio = -1   # Variable temporal
for i in range(n):
    # Anem iterant per les files comparant amb cadascuna de les files
    if np.array_equal(a_comparar, D[i,:]):
        posicio = i
        break
        
print('Posicio: ',  posicio, ' fila hi podem trobar ', a_comparar)

# i una ajuda diferent a Numpy que serveix de recordatori...

conjunt = set()
conjunt.add(3)
conjunt.add(3)
conjunt.add(3)
conjunt.add(3)
print(conjunt)

conjunt.add(1)
conjunt.add(5)
conjunt.add(7)
print(conjunt)

print('L\'element mes petit del conjunt es: ', min(conjunt))

# o...

# En el mon Real hi tenim...
elements = np.matrix([[0, 1, 2, 3, 4, 5, 6]])
print(elements)

# I en el mon Binari hi tindrem...
elements = elements % 2
print(elements)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14  5]
 [16 17  0 19  5]
 [20 21 22 23 24]]
Primera fila:  [[1 2 3 4 5]]
Primera columna:  [[ 1]
 [ 6]
 [11]
 [16]
 [20]]
Tres primeres files, i dos primeres columnes 
[[ 1  2]
 [ 6  7]
 [11 12]]
Quants elements no-zeros hi han a la quarta fila? 4
Quants elements diferents a 5 hi han a la cinquena columna? 2
L'element  [[5]]  de la cinquena columna es diferent a 5 :  [[False]]
L'element  [[10]]  de la cinquena columna es diferent a 5 :  [[ True]]
L'element  [[5]]  de la cinquena columna es diferent a 5 :  [[False]]
L'element  [[5]]  de la cinquena columna es diferent a 5 :  [[False]]
L'element  [[24]]  de la cinquena columna es diferent a 5 :  [[ True]]
A la fila  0  hi tenim  [[1 2 3 4 5]]  amb  5  numeros de zeros
A la fila  1  hi tenim  [[ 6  7  8  9 10]]  amb  5  numeros de zeros
A la fila  2  hi tenim  [[11 12 13 14  5]]  amb  5  numeros de zeros
A la fila  3  hi tenim  [[16 17  0 19  5]]  amb  4  numeros de zeros
A la fila  4  hi ten