# Pràctica 3: Codi Hamming

Després de l'éxit de la primera pràctica amb la vostra implementació en la codificació de missatges espacials, l'Agència Espacial Europea us ha encarregat d'enfortir el seu canal de comunicació a través d'utilitzar codis Hamming.

L'objectiu d'aquesta sessió és que entengueu bé l'ús dels codis de Hamming, així com detectar i corregir errors produits pel mateix medi (radiació Solar que afecta les vostres antenes... o qui sap si són extraterrestres que volen corrompre la vostra comunicació amb la Terra per tal que no els descobriu...).

Ja sabeu codificar de manera aritmètica, però és important saber com assegurar-nos que el missatge que envieu, és el mateix missatge que arriba, i en cas que no, com ho podem solucionar!


**0.** Familiaritzeu-vos amb les següents variables, que són, el codi $C$, la seva matriu de control $H$, així com les dues seqüències.

Aquesta informació seràn els vostres paràmetres de cadascuna de les funcions que us demanarem que implementeu per aquesta sessió de pràctica.

$Nota$: Recordeu que les cel·les de la llibreta Jupiter tenen memòria, és a dir, que cel·les executades posteriorment, tenen definides les variables de les cel·les anteriors.

In [1]:
import numpy as np
import math
import ast
#Ast es una llibreria per ajudar a visualitzar les matrius simplement

def generarCodis(n):
    ldc = []
    for a in [ str('{0:0'+str(n)+'b}').format(x) for x in range(2**n)]:
        a = " ".join(a).split()
        z = []
        for j in a:
            z.append(int(j))
        ldc.append(z)
    return np.matrix(ldc)

def longitudCodi(C):
    return C.shape[1]

def dimensioCodi(C):
    return math.log(C.shape[0], 10)/math.log(2, 10)

def distanciaMinima(C):
    dH = set()
    for u in C:
        for v in C:
            if not np.array_equal(u, v):
                dH.add(np.count_nonzero(np.bitwise_xor(u,v) == 1))
    return min(dH)

def capacitatCorrectora(C):
    d = distanciaMinima(C)
    return abs(d-1)/2


H = np.matrix([(1, 1, 0, 1, 1, 0, 0), (1, 1, 1, 0, 0, 1, 0), (1, 0, 1, 1, 0, 0, 1)])
C = np.matrix([
    (0, 0, 0, 0, 0, 0, 0),
    (0, 0, 0, 1, 1, 0, 1),
    (0, 0, 1, 0, 0, 1, 1),
    (0, 0, 1, 1, 1, 1, 0),
    (0, 1, 0, 0, 1, 1, 0),
    (0, 1, 0, 1, 0, 1, 1),
    (0, 1, 1, 0, 1, 0, 1),
    (0, 1, 1, 1, 0, 0, 0),
    (1, 0, 0, 0, 1, 1, 1),
    (1, 0, 0, 1, 0, 1, 0),
    (1, 0, 1, 0, 1, 0, 0),
    (1, 0, 1, 1, 0, 0, 1),
    (1, 1, 0, 0, 0, 0, 1),
    (1, 1, 0, 1, 1, 0, 0),
    (1, 1, 1, 0, 0, 1, 0),
    (1, 1, 1, 1, 1, 1, 1)])

sequenciaCodificar = np.matrix([(1, 1, 1, 0), (0, 0, 0, 1), (1, 1, 0, 1)])
sequenciaDescodificar = np.matrix([(1, 1, 1, 1, 0, 0, 0), (0, 0, 0, 1, 1, 1, 1), (1, 1, 0, 1, 0, 0, 0)])

print('La meva matriu de control es: \n', H)
print('El meu codi es: \n', C)


La meva matriu de control es: 
 [[1 1 0 1 1 0 0]
 [1 1 1 0 0 1 0]
 [1 0 1 1 0 0 1]]
El meu codi es: 
 [[0 0 0 0 0 0 0]
 [0 0 0 1 1 0 1]
 [0 0 1 0 0 1 1]
 [0 0 1 1 1 1 0]
 [0 1 0 0 1 1 0]
 [0 1 0 1 0 1 1]
 [0 1 1 0 1 0 1]
 [0 1 1 1 0 0 0]
 [1 0 0 0 1 1 1]
 [1 0 0 1 0 1 0]
 [1 0 1 0 1 0 0]
 [1 0 1 1 0 0 1]
 [1 1 0 0 0 0 1]
 [1 1 0 1 1 0 0]
 [1 1 1 0 0 1 0]
 [1 1 1 1 1 1 1]]


**1.** Dissenyeu la funció $ParametresCodi(C)$ que, donat un codi $C$, en retorni $(n,k,d), t$ on $n$ és la longitud, $k$ la dimensió i $d$ la distància mínima, i $t$ la capacitat correctora.

Utilitzeu les funcions $longitudCodi(C)$, $dimensioCodi(C)$, $distanciaMinimaCodi(C)$ i $capacitatCorrectora(C)$ que s'utilitzen per al càlcul general de paràmetres per codis lineals.

Mostreu per pantalla el resultat de $ParametresCodi(C)$ passant com a paràmetre el vostre codi.

In [2]:
def ParametresCodi(C):
    n = longitudCodi(C)
    k = dimensioCodi(C)
    d = distanciaMinima(C)
    t = capacitatCorrectora(C)
    return (n,k,d),t

parametres, corrector = ParametresCodi(C)
print(parametres)
print(corrector)

(7, 4.0, 3)
1.0


**2.** Donat el nombre de bits redundants, el paràmetre $r$, i sabent que es tracta d'un codi de Hamming, implementeu les funcions $longitudCodiHamming(r)$, $dimensioCodiHamming(r)$ i $distanciaCodiHamming()$.

Recordeu que, per qualsevol codi de Hamming, es compleix :

* n = 2<sup>r</sup> - 1
* k = n - r
* d = 3

Comprova el resultat de les teves funcions és el mateix que utilitzant les de codi lineal general amb codi $C$, tenint en compte que $r = 3$.


In [3]:
def longitudCodiHamming(r):
    return (2**r) -1

def dimensioCodiHamming(r):
    return longitudCodiHamming(r) - r

def distanciaCodiHamming():
    return 3

assert(longitudCodiHamming(3) == longitudCodi(C))
assert(dimensioCodiHamming(3) == dimensioCodi(C))
assert(distanciaCodiHamming() == distanciaMinima(C))
print("Tot correcte!")

Tot correcte!


**3.** Calculeu la matriu generadora $G$ a partir de la matriu de control $H$, sabent que $H$ conté la matriu identitat en les últimes $r$ columnes. Comproveu que les matrius són ortogonals entre si.
Es tracta d’una matriu sistemàtica? Per què? Respon a les dues preguntes a una cel·la de text **addicional**.

In [4]:
def calcula_generadora(H):

    P_transposed = H[:,:H.shape[1]-H.shape[0]]
    identitat = np.identity(H.shape[1] - H.shape[0], dtype = "int")
    G = np.concatenate((identitat,-np.transpose(P_transposed)), axis = 1)
    return G

def comprova_ortogonal(H, G):
  return np.dot(H,np.transpose(G))

print(comprova_ortogonal(H, calcula_generadora(H)),"És ortogonal\n")
G = np.abs(calcula_generadora(H))
print("Matriu Generadora:\n", G)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] És ortogonal

Matriu Generadora:
 [[1 0 0 0 1 1 1]
 [0 1 0 0 1 1 0]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 0 1]]


**Comproveu que les matrius són ortogonals entre si.**
Sí que són ortogonals ja que obtenim la matriu amb tot zeros [[0,0,0,0],[0,0,0,0],[0,0,0,0]].

**Es tracta d’una matriu sistemàtica? Per què?**
És una matriu sistemàtica perquè inclou una matriu identitat a les primeres posicions. Per tant, les columnes restants són combinacions lineals de les columnes de la matriu identitat. Les matrius que es poden descomposar com G=[I
​
 ∣P] esdevenen sistemàtiques.

**4.** Implementeu la funció $CodificaHamming(G, m)$ que donada la vostra matriu generadora $G$ i un vector binari d'informació $m$ de longitud $k$, retorni el vector codificat.

Escolliu un vector binari d'informació $m$ de longitud $k$.

Fent servir la funció $CodificaHamming(G, m)$, doneu el vector codificat $v$, dient-ne quin és el valor i la seva longitud del vector que heu escollit, així com pel codificat $v$.

In [5]:
def CodificaHamming(G, m):
    m = np.array(m)
    if m.ndim != 1:
        raise ValueError("El vector ha de ser unidimensional")

    v = np.dot(m, G) % 2

    return np.array(v.tolist()[0])

m = [1, 0, 1, 1]
v = CodificaHamming(G, m)

print("Vector d'informació m:", m)
print("Longitud del vector de informació:", len(m))
print("Vector codificat v:", v)
print("Longitud del vector codificat:", len(v))


Vector d'informació m: [1, 0, 1, 1]
Longitud del vector de informació: 4
Vector codificat v: [1 0 1 1 0 0 1]
Longitud del vector codificat: 7


**5.** Implementeu la funció $DescodificaHamming(H, w)$, que, donant una matriu de control $H$, i un vector binari $w$ de longitud $n$, en retorni:

* La sindrome de $w$
* El vector $w$ corregit (v')
* El vector d'informacio corresponent (m')

Utilitzeu les funcions $longitudCodiHamming(r)$ i $dimensioCodiHamming(r)$ que heu implementat anteriorment, amb $r=3$.


In [6]:
def sindrome(w, H):
    s = np.dot(w, H.T) % 2
    return str(s.tolist()[0])

def creacio_dict(n, H, r):
    error_dict = {}
    error_dict[str([0]*r)] = np.zeros(n, dtype = "int")
    identitat = np.identity(n, dtype = "int")
    for fila in identitat:
      error_dict[sindrome(fila, H)] = np.array(fila)

    return error_dict


def DescodificaHamming(H, w):
    r = 3
    k = dimensioCodiHamming(r)
    e_dict = creacio_dict(k+r, H, r)
    s = sindrome(w, H)
    for sind, error in e_dict.items():
      if s == sind:
        corrected = (w + error) % 2

    return s, corrected, corrected[:k]


**6.** Considereu un vector $w$ on sabem que s'ha produït un error respecte al vector $v$ de l'apartat de la Codificació.

Fent servir la funció $DescodificaHamming(H, w)$, doneu la síndrome de $w$, el vector $w$ després de corregir l'error i el vector d'informació.

Feu el mateix, però, afegint dos errors al vector codificat $v$.

Com podeu interpretar els dos resultats tenint en compte els paràmetres del codi? Responeu a la pregunta a una cel·la de text **addicional**.


In [7]:
w = CodificaHamming(G, [1,0,1,1])
print("Vector Codificat inicial:",w)

#Modifquem un valor perquè s'ha de produir un error
w[0] = (w[0] + 1) % 2

print("Vector amb error a la posició 0:", w,"\n")

s, wc, inf = DescodificaHamming(H,w)

print("síndrome:",s)
print("vector w corregit:",wc)
print("vector informació",inf)

Vector Codificat inicial: [1 0 1 1 0 0 1]
Vector amb error a la posició 0: [0 0 1 1 0 0 1] 

síndrome: [1, 1, 1]
vector w corregit: [1 0 1 1 0 0 1]
vector informació [1 0 1 1]


In [8]:
w = CodificaHamming(G, [1,0,1,1])
print("Vector Codificat inicial:",w)

#Modifiquem el vector per tenir dos errors
w[1] = (w[1] + 1) % 2
w[0] = (w[0] + 1) % 2


print("Vector amb error a la posició 0 i 1:", w,"\n")

s, wc, inf = DescodificaHamming(H,w)

print("síndrome:",s)
print("vector w corregit:",wc)
print("vector informació",inf)

Vector Codificat inicial: [1 0 1 1 0 0 1]
Vector amb error a la posició 0 i 1: [0 1 1 1 0 0 1] 

síndrome: [0, 0, 1]
vector w corregit: [0 1 1 1 0 0 0]
vector informació [0 1 1 1]


**Com podeu interpretar els dos resultats tenint en compte els paràmetres del codi?**
En el codi de Hamming, es pot observar que amb un sol error, la descodificació és capaç de detectar i corregir l'error amb èxit "[1,0,1,1]". No obstant, amb dos errors és incapaç de reconstruir el vector inicial "[0,1,1,1] != [1,0,1,1]". Amb aquest exemple es confirma que el codi hamming és capaç de corregir un error, però no més d'un, tal i com es va explicar a classe.

**7.** Considereu la matriu generadora, i la matriu d'informació $sequenciaCodificar$ definida a la primera cel·la, que correspon a una matriu amb $k$ columnes.

Fent servir la funció $CodificaHamming(G, m)$, codifiqueu la informació en forma de matriu.

In [9]:
files_codificades = []

for fila in sequenciaCodificar:
    files_codificades.append(CodificaHamming(G, fila.tolist()[0]))

print(np.matrix(files_codificades))

[[1 1 1 0 0 1 0]
 [0 0 0 1 1 0 1]
 [1 1 0 1 1 0 0]]


**8.** Modifiqueu la funció $DescodificaHamming(H, W)$ vista anteriorment, per tal que, donada una matriu $W$ on a cada fila hi ha un vector binari $W_{i}$, de longitud $n$, i fent servir el vostre codi Hamming, retorni:

* La matriu de síndromes on a cada fila hi ha la síndrome de $W_{i}$
* La matriu w amb els errors corregits ($v'$)
* La matriu d'informació on a cada fila hi ha el vector d'informació corresponent a la fila $W_{i}$ ($m'$).


Descodifiqueu i doneu els resultats de la funció $DescodificaHamming(H, w)$ on $w$ correspon al vector $sequenciaDescodificar$ definit a la primera cel·la, transformant-la primer en una matriu amb $n$ columnes.


In [10]:
def DescodificaHamming(H, w):
    r = 3
    k = dimensioCodiHamming(r)
    e_dict = creacio_dict(k+r, H, r)
    s_list = []
    corrected_list = []
    inf_list = []

    for fila in w:
      fila = fila.tolist()[0]
      s = sindrome(fila, H)
      for sind, error in e_dict.items():
        if s == sind:
          corrected = (fila + error) % 2
          s_list.append(ast.literal_eval(s))
          corrected_list.append(corrected)
          inf_list.append(corrected[:k])

    return np.matrix(s_list), np.matrix(corrected_list), np.matrix(inf_list)

matriu_sindrome,w,info=DescodificaHamming(H, sequenciaDescodificar)

print(f'Matriu síndrome: \n{matriu_sindrome}')
print(f'\nMatriu w amb els errors corregits: \n{w}')
print(f'\nMatriu informació: \n {info}')

Matriu síndrome: 
[[1 1 1]
 [0 1 0]
 [1 0 0]]

Matriu w amb els errors corregits: 
[[0 1 1 1 0 0 0]
 [0 0 0 1 1 0 1]
 [1 1 0 1 1 0 0]]

Matriu informació: 
 [[0 1 1 1]
 [0 0 0 1]
 [1 1 0 1]]
